spring:
  webdav:
    host: http://127.0.0.1:8080 #指定host
    path: /webdav/project #指定跟路径
    scope: luna #指定项目scope 可选，后续上传可自定义scpoe
    max-total: 80 # 最大链接数量 优化httpclient
    default-max-per-route: 100 # 每个路由的最大链接数量 优化httpclient
    username: luna # webdav 的basic配置用户名
    password: luna # webdav 的basic配置密码
    auth-type: digest # webdav 认证类型，可选basic，digest，暂不支持：ntlm，kerberos，spnego，negotiate
    openLog: true # 是否开启日志
